managers:
  hosts:
    master1:
      ansible_host: 192.168.0.109
workers:
  hosts:
    worker1:
      ansible_host: 192.168.0.110
    worker2:
      ansible_host: 192.168.0.110
cluster:
  children:
    managers:
    workers:
