global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: '$1:9100'
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance

  - job_name: "container_status"
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep

      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: .+
        action: keep
      
      - source_labels: [__address__]
        regex: ^(172.28).+
        action: keep

      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]      
        target_label: job

      - source_labels: [__address__, __meta_dockerswarm_container_label_prometheus_port]
        separator: ';'
        regex: (.*):(.*);(.*)
        replacement: ${1}:${3}
        target_label: __address__
      
      - source_labels: [__meta_dockerswarm_node_hostname, __meta_dockerswarm_container_label_prometheus_port]
        separator: ';'
        regex: (.*);(.*)
        replacement: ${1}:${2}
        target_label: instance